version: "3.3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/core
    ports:
      - 3000:3000
    image: app:react-app1
    container_name: react_container
    command: npm start
